---
#
# Ansible managed
#
repository:
  description: Install and configure nginx on your system.
  homepage: https://robertdebock.nl/
  topics: nginx, web, installer, networking, ansible, molecule, tox, playbook
