---
# tasks file for nginx
- name: install software
  package:
    name: nginx
    state: present

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: ensure /etc/nginx/conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: place default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: start service
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
