---
# tasks file for ansible-role-nginx
- name: install software
  package:
    name: nginx

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    
- name: place default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: start and enable software
  systemd:
    name: nginx
    state: started
    enabled: true
