---
# tasks file for nginx
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: nginx

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify:
    - restart nginx

- name: ensure /etc/nginx/conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: place default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: start service
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
