---
# tasks file for ansible-role-nginx
- name: install software
  package:
    name: nginx
    state: present

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: place default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: start service
  include: "{{ item }}"
  with_first_found:
    - service-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml
    - service-{{ ansible_distribution }}.yml
    - service-default.yml
