---
# tasks file for ansible-role-nginx
- name: install software
  package:
    name: nginx

- name: place nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    
- name: place default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: start and enable software
  systemd:
    name: nginx
    state: started
    enabled: true

- name: start and enable nginx using systemd
  systemd:
    name: nginx
    state: started
    enabled: yes
  when:
    - ( ansible_distribution == "Fedora" or ( ansible_distribution == "Centos" and ansible_distribution_major_version == "7" ) )

- name: start and enable docker using service
  service:
    name: nginx
    state: started
    enabled: yes
  when:
    - ( ansible_distribution == "Alpine" or ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" )
