---
- name: Prepare
  hosts: all
  gather_facts: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel

  tasks:
    - name: test nginx
      shell: nginx -V > nginx.version
      args:
        creates: nginx.version
