---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nginx-ubuntu-devel
    image: ubuntu:devel
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        nginx_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-devel
