---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.nginx

  tasks:
    - name: test nginx
      shell: nginx -V > nginx.version
      args:
        creates: nginx.version
