---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-6
    image: centos:6
  - name: centos-7
    image: centos:7
  - name: debian-jessie
    image: debian:jessie
  - name: debian-buster
    image: debian:buster
  - name: fedora-26
    image: fedora:26
  - name: fedora-27
    image: fedora:27
  - name: ubuntu-zesty
    image: ubuntu:zesty
  - name: ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
