---
- name: Converge
  hosts: all
  gather_facts: no
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: ansible-role-nginx

  tasks:
    - name: test nginx
      shell: nginx -V > nginx.version
      args:
        creates: nginx.version
